# Function to generate friend declarations for operators
function(generate_operator_friend_declarations OPERATOR_DIR OUTPUT_FILE)
    message(STATUS "Generating operator friend declarations from: ${OPERATOR_DIR}")
    message(STATUS "Output file: ${OUTPUT_FILE}")
    
    # Find all operator header files
    file(GLOB OPERATOR_HEADERS "${OPERATOR_DIR}/*.hpp")
    
    # Initialize output content
    set(FRIEND_DECLARATIONS "")
    
    # Process each operator header
    foreach(HEADER_FILE ${OPERATOR_HEADERS})
        # Read the header file
        file(READ ${HEADER_FILE} FILE_CONTENT)
        
        # Extract namespace Operator content
        string(REGEX MATCH "namespace[ \t]+Operator[ \t]*{([^}]*)}" 
               NAMESPACE_MATCH "${FILE_CONTENT}")
        
        if(NAMESPACE_MATCH)
            set(NAMESPACE_CONTENT "${CMAKE_MATCH_1}")
            
            # Find function declarations that return Genome
            # Updated regex to handle multiline function declarations
            string(REGEX MATCHALL "Genome[ \t]+([A-Za-z_][A-Za-z0-9_]*)[ \t]*\\([^{;]*\\)" 
                   FUNCTION_MATCHES "${NAMESPACE_CONTENT}")
            
            foreach(FUNCTION_MATCH ${FUNCTION_MATCHES})
                # Extract function signature with better multiline handling
                string(REGEX MATCH "Genome[ \t]+([A-Za-z_][A-Za-z0-9_]*)[ \t]*\\(([^{;]*)\\)" 
                       SIGNATURE_MATCH "${FUNCTION_MATCH}")
                
                if(SIGNATURE_MATCH)
                    set(FUNCTION_NAME "${CMAKE_MATCH_1}")
                    set(FUNCTION_PARAMS "${CMAKE_MATCH_2}")
                    
                    # Clean up parameters (remove extra whitespace and newlines)
                    string(REGEX REPLACE "[ \t\n\r]+" " " CLEAN_PARAMS "${FUNCTION_PARAMS}")
                    string(STRIP "${CLEAN_PARAMS}" CLEAN_PARAMS)
                    
                    # Add friend declaration (fully qualified with namespace)
                    string(APPEND FRIEND_DECLARATIONS 
                           "\tfriend Genome Operator::${FUNCTION_NAME}(${CLEAN_PARAMS});\n")
                endif()
            endforeach()
        endif()
    endforeach()
    
    # Generate complete include content
    set(INCLUDE_CONTENT "// Auto-generated friend declarations for operators\n")
    string(APPEND INCLUDE_CONTENT "// This file is generated by CMake - do not edit manually\n")
    string(APPEND INCLUDE_CONTENT "// Include this in the protected section of data structure classes\n\n")
    string(APPEND INCLUDE_CONTENT "${FRIEND_DECLARATIONS}")
    
    # Write output file
    file(WRITE ${OUTPUT_FILE} "${INCLUDE_CONTENT}")
    
    # Report what was generated
    message(STATUS "Generated operator friend declarations in ${OUTPUT_FILE}")
endfunction()